#!/bin/zsh

sudo docker run -d \
    --restart=unless-stopped \
    --net=host \
    --name=unifi \
    -e TZ='America/Los_Angeles' \
    -e UNIFI_UID=1000 \
    -e UNIFI_GID=1000 \
    -v /home/jl/docker/unifi:/unifi \
    jacobalberty/unifi:stable
